version: "3.6"

x-build-args: &build_args
  PYTHON_IMAGE_VERSION: slim-buster
  NODE_IMAGE_VERSION: slim


services:
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
      - type: bind
        source: ./my.cnf
        target: /etc/my.cnf
        read_only: true
        
  backend:
    build:
      context: ./backend
      target: development
      args:
        <<: *build_args
    depends_on:
      - database
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 0
    volumes:
      - type: bind
        source: ./backend
        target:  /backend

  manage:
    build:
      context: ./backend/
      target: development
      args:
        <<: *build_args
    depends_on:
      - database
    env_file: .env
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./backend
        target:  /backend

  frontend:
    build:
      context: ./frontend/
      target: development
      args:
        <<: *build_args
    depends_on:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./frontend
        target:  /app
        read_only: true


volumes:
  db_data:
